### ISSUE TITLE
Request to collaborate

### ISSUE THREAD

**Issue by BenWeisz** [adisonyheathcott/PPMViewer#13]
Hi!

I'm a collaborator on another PPM/PGM file previewer: [Link](https://github.com/nagata-yoshiteru/ppm-pgm-viewer-for-vscode)
I was wondering if you guys wanted to join forces and consolidate our work / experience in this repo ^

Hope to hear back from you :)

**Comment by adisonyheathcott** [comment]
Hey Ben.

I appreciate you reaching out with the opportunity but I do not have the time to pick up another project. I started this project back when vscode had no addons for ppm files out of necessity and didn't really plan on updating it normally. Sadly I don't have the time to put the love into this project that I'd like to. The other contributors are doing so with no association to me so maybe they would be open to an offer directly.

I wish you and your partners the best in all future endeavors. :)
