### ISSUE TITLE
[Bug] "View PPM" displays blank tab

### ISSUE THREAD

**Issue by ErwanDL** [adisonyheathcott/PPMViewer#6]
Hi ! I have downloaded your VScode extension to try and view some PPM files, but I have not gotten it to work so far.

I was trying to view the following PPM file using the `View PPM` command, and a new tab was opened named "PPM View" but nothing was displayed in it.

<img width="977" alt="Screen Shot 2020-03-29 at 12 11 21 PM" src="https://user-images.githubusercontent.com/35762435/77858139-6cb4db80-71b6-11ea-9323-a1f159b6559a.png">

<details>
<summary>PPM source file</summary>
P3
60 40
255
87 35 35 88 35 35 90 36 36 91 36 36 92 37 37 93 37 37 95 38 38 96 38 38 97 39 39 99 39 39 100 40 40 101 40 40 103 41 41 104 42 42 106 42 42 107 43 43 109 44 44 110 44 44 112 45 45 113 46 46 115 46 46 117 47 47 118 48 48 120 49 49 121 49 49 122 50 50 123 51 51 124 51 51 125 51 51 125 52 52 125 52 52 125 52 52 125 51 51 124 51 51 124 51 51 123 50 50 122 49 49 120 49 49 119 48 48 118 48 48 117 47 47 115 46 46 114 46 46 113 45 45 111 45 45 110 44 44 109 43 43 107 43 43 106 42 42 105 42 42 104 41 41 102 41 41 101 40 40 100 40 40 99 39 39 97 39 39 96 38 38 95 38 38 94 37 37 93 37 37 87 35 35 89 35 35 90 36 36 91 36 36 92 37 37 94 37 37 95 38 38 96 38 38 97 39 39 99 39 39 100 40 40 102 41 41 103 41 41 105 42 42 106 42 42 108 43 43 109 44 44 111 45 45 113 45 45 114 46 46 116 47 47 118 48 48 119 49 49 121 50 50 123 50 50 124 51 51 125 52 52 126 52 52 127 52 52 127 53 53 127 53 53 127 53 53 127 52 52 126 52 52 125 52 52 124 51 51 123 50 50 122 50 50 121 49 49 119 48 48 118 48 48 116 47 47 115 46 46 114 46 46 112 45 45 111 44 44 109 44 44 108 43 43 107 43 43 105 42 42 104 42 42 103 41 41 102 40 40 100 40 40 99 39 39 98 39 39 97 38 38 95 38 38 94 38 38 93 37 37 88 35 35 89 35 35 90 36 36 91 36 36 92 37 37 94 37 37 95 38 38 96 38 38 98 39 39 99 40 40 101 40 40 102 41 41 103 41 41 105 42 42 107 43 43 108 43 43 110 44 44 112 45 45 113 46 46 115 47 47 117 47 47 119 48 48 121 49 49 122 50 50 124 51 51 125 52 52 127 53 53 128 53 53 129 54 54 129 54 54 129 54 54 129 54 54 129 54 54 128 53 53 127 53 53 126 52 52 125 51 51 123 50 50 122 50 50 120 49 49 119 48 48 117 47 47 116 47 47 114 46 46 113 45 45 111 45 45 110 44 44 109 43 43 107 43 43 106 42 42 105 42 42 103 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 94 38 38 93 37 37 88 35 35 89 35 35 90 36 36 91 36 36 93 37 37 94 37 37 95 38 38 97 39 39 98 39 39 99 40 40 101 40 40 102 41 41 104 41 41 105 42 42 107 43 43 109 44 44 110 44 44 112 45 45 114 46 46 116 47 47 118 48 48 120 49 49 122 50 50 124 51 51 125 52 52 127 53 53 128 54 54 130 54 54 130 55 55 131 55 55 131 55 55 131 55 55 131 55 55 130 54 54 129 54 54 128 53 53 126 52 52 125 51 51 123 50 50 122 50 50 120 49 49 118 48 48 117 47 47 115 46 46 114 46 46 112 45 45 111 44 44 109 44 44 108 43 43 106 43 43 105 42 42 104 41 41 102 41 41 101 40 40 100 40 40 98 39 39 97 39 39 96 38 38 95 38 38 94 37 37 88 35 35 89 36 36 90 36 36 91 36 36 93 37 37 94 38 38 95 38 38 97 39 39 98 39 39 100 40 40 101 40 40 102 41 41 104 42 42 106 42 42 107 43 43 109 44 44 111 45 45 112 45 45 114 46 46 116 47 47 118 48 48 121 49 49 123 51 51 125 52 52 127 53 53 128 54 54 130 55 55 131 55 55 132 56 56 133 56 56 133 56 56 133 56 56 132 56 56 131 55 55 130 55 55 129 54 54 128 53 53 126 52 52 124 51 51 123 50 50 121 49 49 119 49 49 118 48 48 116 47 47 114 46 46 113 45 45 111 45 45 110 44 44 108 43 43 107 43 43 105 42 42 104 42 42 103 41 41 101 40 40 100 40 40 99 39 39 97 39 39 96 38 38 95 38 38 94 37 37 88 35 35 89 36 36 90 36 36 92 37 37 93 37 37 94 38 38 95 38 38 97 39 39 98 39 39 100 40 40 101 40 40 103 41 41 104 42 42 106 42 42 107 43 43 109 44 44 111 45 45 113 46 46 115 47 47 117 48 48 119 49 49 121 50 50 123 51 51 126 52 52 128 53 53 130 54 54 131 55 55 133 56 56 134 57 57 134 57 57 135 57 57 134 57 57 134 57 57 133 56 56 132 56 56 79 79 183 96 96 218 100 100 229 99 99 230 97 97 225 122 50 50 120 49 49 118 48 48 117 47 47 115 46 46 113 46 46 112 45 45 110 44 44 109 43 43 107 43 43 106 42 42 104 42 42 103 41 41 102 41 41 100 40 40 99 39 39 98 39 39 96 38 38 95 38 38 94 37 37 88 35 35 89 36 36 90 36 36 92 37 37 93 37 37 94 38 38 96 38 38 97 39 39 98 39 39 100 40 40 101 40 40 103 41 41 104 42 42 106 42 42 108 43 43 109 44 44 111 45 45 113 46 46 115 47 47 117 48 48 120 49 49 122 50 50 124 52 52 126 53 53 129 54 54 131 55 55 132 56 56 134 57 57 135 58 58 136 58 58 136 58 58 136 58 58 136 58 58 135 57 57 69 69 160 91 91 203 89 89 206 92 92 215 95 95 221 95 95 221 91 91 212 121 50 50 119 49 49 117 48 48 116 47 47 114 46 46 112 45 45 111 44 44 109 44 44 107 43 43 106 42 42 105 42 42 103 41 41 102 41 41 100 40 40 99 40 40 98 39 39 97 39 39 95 38 38 94 38 38 88 35 35 89 36 36 90 36 36 92 37 37 93 37 37 94 38 38 96 38 38 97 39 39 98 39 39 100 40 40 101 40 40 103 41 41 104 42 42 106 42 42 108 43 43 109 44 44 111 45 45 113 46 46 115 47 47 118 48 48 120 49 49 122 51 51 125 52 52 127 53 53 129 55 55 131 56 56 133 57 57 135 58 58 136 59 59 137 59 59 137 59 59 137 59 59 137 59 59 51 51 119 65 65 152 74 74 172 80 80 187 85 85 197 89 89 206 88 88 204 85 85 198 78 78 181 120 49 49 118 48 48 116 47 47 114 46 46 113 45 45 111 45 45 109 44 44 108 43 43 106 42 42 105 42 42 103 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 95 38 38 94 38 38 88 35 35 89 36 36 90 36 36 92 37 37 93 37 37 94 38 38 95 38 38 97 39 39 98 39 39 100 40 40 101 40 40 103 41 41 104 42 42 106 42 42 108 43 43 109 44 44 111 45 45 113 46 46 115 47 47 118 48 48 120 50 50 123 51 51 125 52 52 127 54 54 130 55 55 132 56 56 134 57 57 136 58 58 137 59 59 138 60 60 138 60 60 139 60 60 138 60 60 48 48 111 58 58 135 66 66 153 71 71 166 78 78 180 255 255 255 85 85 196 82 82 191 77 77 179 120 49 49 118 48 48 116 47 47 115 46 46 113 46 46 111 45 45 109 44 44 108 43 43 106 43 43 105 42 42 103 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 94 38 38 88 35 35 89 36 36 90 36 36 92 36 36 93 37 37 94 38 38 95 38 38 97 39 39 98 39 39 100 40 40 101 40 40 102 41 41 104 42 42 106 42 42 107 43 43 109 44 44 111 45 45 113 46 46 115 47 47 118 48 48 120 50 50 123 51 51 125 52 52 128 54 54 130 55 55 132 57 57 135 58 58 136 59 59 138 60 60 139 60 60 139 61 61 139 61 61 139 60 60 40 40 94 50 50 116 59 59 137 66 66 154 72 72 167 76 76 176 77 77 180 76 76 178 72 72 167 55 55 128 119 49 49 117 48 48 115 47 47 113 46 46 111 45 45 110 44 44 108 43 43 106 43 43 105 42 42 104 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 94 38 38 88 35 35 89 35 35 90 36 36 91 36 36 93 37 37 94 37 37 95 38 38 97 39 39 98 39 39 99 40 40 101 40 40 102 41 41 104 42 42 105 42 42 107 43 43 109 44 44 111 45 45 113 46 46 115 47 47 118 48 48 120 50 50 123 51 51 125 53 53 128 54 54 130 55 55 133 57 57 135 58 58 137 59 59 138 60 60 139 61 61 140 61 61 140 61 61 140 61 61 34 34 78 44 44 103 53 53 123 60 60 139 65 65 151 68 68 159 70 70 163 69 69 160 64 64 149 121 50 50 119 49 49 117 48 48 115 47 47 113 46 46 111 45 45 110 44 44 108 43 43 106 43 43 105 42 42 104 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 94 38 38 88 35 35 89 35 35 90 36 36 91 36 36 93 37 37 94 37 37 95 38 38 96 38 38 98 39 39 99 40 40 101 40 40 102 41 41 104 41 41 105 42 42 107 43 43 109 44 44 111 45 45 113 46 46 115 47 47 117 48 48 120 50 50 122 51 51 125 53 53 128 54 54 130 56 56 133 57 57 135 58 58 137 59 59 138 60 60 140 61 61 140 62 62 140 62 62 140 61 61 29 29 68 38 38 88 46 46 106 52 52 121 57 57 132 60 60 139 61 61 142 59 59 138 54 54 125 122 50 50 119 49 49 117 48 48 115 47 47 113 46 46 111 45 45 110 44 44 108 43 43 106 43 43 105 42 42 103 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 95 38 38 94 38 38 88 35 35 89 35 35 90 36 36 91 36 36 92 37 37 94 37 37 95 38 38 96 38 38 97 39 39 99 39 39 100 40 40 102 41 41 103 41 41 105 42 42 107 43 43 108 44 44 110 45 45 112 46 46 115 47 47 117 48 48 119 49 49 122 51 51 125 52 52 127 54 54 130 55 55 132 57 57 135 58 58 137 59 59 138 60 60 139 61 61 140 62 62 140 62 62 140 62 62 29 29 68 29 29 69 37 37 87 43 43 100 47 47 110 50 50 116 50 50 118 48 48 112 39 39 90 122 51 51 119 49 49 117 48 48 115 47 47 113 46 46 111 45 45 110 44 44 108 43 43 106 43 43 105 42 42 103 41 41 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 95 38 38 94 38 38 87 35 35 89 35 35 90 36 36 91 36 36 92 37 37 93 37 37 95 38 38 96 38 38 97 39 39 99 39 39 100 40 40 101 41 41 103 41 41 105 42 42 106 43 43 108 44 44 110 45 45 112 46 46 114 47 47 116 48 48 119 49 49 121 51 51 124 52 52 127 54 54 129 55 55 132 57 57 134 58 58 136 59 59 138 60 60 139 61 61 140 62 62 140 62 62 140 62 62 139 61 61 29 29 68 29 29 68 33 33 77 37 37 85 39 39 90 38 38 89 33 33 77 124 52 52 122 51 51 119 49 49 117 48 48 115 47 47 113 46 46 111 45 45 109 44 44 108 43 43 106 43 43 105 42 42 103 41 41 102 41 41 100 40 40 99 40 40 98 39 39 96 38 38 95 38 38 94 37 37 87 35 35 88 35 35 89 36 36 91 36 36 92 37 37 93 37 37 94 38 38 96 38 38 97 39 39 98 39 39 100 40 40 101 40 40 103 41 41 104 42 42 106 43 43 108 43 43 109 44 44 111 45 45 114 46 46 116 48 48 118 49 49 121 50 50 123 52 52 126 53 53 128 55 55 131 56 56 133 58 58 135 59 59 137 60 60 138 61 61 139 61 61 140 62 62 140 62 62 139 61 61 138 61 61 29 29 68 29 29 68 29 29 68 29 29 68 129 55 55 126 53 53 124 52 52 121 51 51 119 49 49 117 48 48 115 47 47 113 46 46 111 45 45 109 44 44 107 43 43 106 42 42 104 42 42 103 41 41 101 41 41 100 40 40 99 39 39 98 39 39 96 38 38 95 38 38 94 37 37 87 35 35 88 35 35 89 36 36 90 36 36 92 36 36 93 37 37 94 37 37 95 38 38 96 38 38 98 39 39 99 40 40 101 40 40 102 41 41 104 42 42 105 42 42 107 43 43 109 44 44 111 45 45 113 46 46 115 47 47 117 49 49 120 50 50 122 51 51 125 53 53 127 54 54 130 56 56 132 57 57 134 58 58 136 60 60 137 60 60 138 61 61 139 61 61 139 61 61 138 61 61 137 60 60 136 59 59 134 58 58 132 57 57 130 56 56 128 55 55 126 53 53 123 52 52 121 50 50 119 49 49 117 48 48 114 47 47 112 46 46 111 45 45 109 44 44 107 43 43 106 42 42 104 42 42 103 41 41 101 40 40 100 40 40 99 39 39 97 39 39 96 38 38 95 38 38 94 37 37 87 35 35 88 35 35 89 35 35 90 36 36 91 36 36 92 37 37 94 37 37 95 38 38 96 38 38 97 39 39 99 39 39 100 40 40 101 41 41 103 41 41 105 42 42 106 43 43 108 44 44 110 45 45 112 46 46 114 47 47 116 48 48 119 49 49 121 51 51 124 52 52 126 54 54 129 55 55 131 57 57 133 58 58 135 59 59 136 60 60 137 60 60 137 61 61 137 61 61 137 60 60 136 60 60 135 59 59 133 58 58 132 57 57 129 56 56 127 54 54 125 53 53 123 52 52 120 50 50 118 49 49 116 48 48 114 47 47 112 46 46 110 45 45 108 44 44 107 43 43 105 42 42 104 42 42 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 95 38 38 93 37 37 86 34 34 87 35 35 89 35 35 90 36 36 91 36 36 92 37 37 93 37 37 94 38 38 96 38 38 97 39 39 98 39 39 100 40 40 101 40 40 102 41 41 104 42 42 106 43 43 107 43 43 109 44 44 111 45 45 113 46 46 115 48 48 118 49 49 120 50 50 122 52 52 125 53 53 127 54 54 129 56 56 131 57 57 133 58 58 134 59 59 135 59 59 136 60 60 136 60 60 136 60 60 135 59 59 134 58 58 132 57 57 130 56 56 128 55 55 126 54 54 124 52 52 122 51 51 120 50 50 117 49 49 115 47 47 113 46 46 111 45 45 109 44 44 108 44 44 106 43 43 105 42 42 103 41 41 102 41 41 100 40 40 99 40 40 98 39 39 97 39 39 95 38 38 94 38 38 93 37 37 86 34 34 87 35 35 88 35 35 89 36 36 90 36 36 92 37 37 93 37 37 94 37 37 95 38 38 96 38 38 98 39 39 99 40 40 100 40 40 102 41 41 103 41 41 105 42 42 106 43 43 108 44 44 110 45 45 112 46 46 114 47 47 116 48 48 119 50 50 121 51 51 123 52 52 126 54 54 128 55 55 130 56 56 131 57 57 132 58 58 133 58 58 134 59 59 134 59 59 134 59 59 133 58 58 132 57 57 131 57 57 129 56 56 127 54 54 125 53 53 123 52 52 121 51 51 119 49 49 116 48 48 114 47 47 112 46 46 111 45 45 109 44 44 107 43 43 106 42 42 104 42 42 103 41 41 101 41 41 100 40 40 99 39 39 97 39 39 96 38 38 95 38 38 94 37 37 93 37 37 86 34 34 87 35 35 88 35 35 89 35 35 90 36 36 91 36 36 92 37 37 93 37 37 95 38 38 96 38 38 97 39 39 98 39 39 100 40 40 101 40 40 102 41 41 104 42 42 106 43 43 107 43 43 109 44 44 111 45 45 113 46 46 115 48 48 117 49 49 119 50 50 122 51 51 124 53 53 49 20 20 49 20 20 49 20 20 49 20 20 131 57 57 132 58 58 132 58 58 132 57 57 131 57 57 130 56 56 129 56 56 127 55 55 126 54 54 124 52 52 122 51 51 120 50 50 117 49 49 115 48 48 113 47 47 112 46 46 110 45 45 108 44 44 106 43 43 105 42 42 103 42 42 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 95 38 38 93 37 37 92 37 37 85 34 34 86 34 34 87 35 35 88 35 35 90 36 36 91 36 36 92 37 37 93 37 37 94 38 38 95 38 38 96 38 38 98 39 39 99 40 40 100 40 40 102 41 41 103 41 41 105 42 42 106 43 43 108 44 44 110 45 45 112 46 46 114 47 47 116 48 48 118 49 49 120 50 50 48 20 20 49 20 20 49 20 20 49 20 20 49 20 20 49 20 20 49 20 20 130 56 56 130 56 56 129 56 56 128 55 55 127 55 55 125 54 54 124 53 53 122 52 52 120 50 50 118 49 49 116 48 48 114 47 47 112 46 46 111 45 45 109 44 44 107 43 43 106 43 43 104 42 42 103 41 41 101 41 41 100 40 40 99 40 40 98 39 39 96 38 38 95 38 38 94 38 38 93 37 37 92 37 37 85 34 34 86 34 34 87 35 35 88 35 35 89 36 36 130 130 0 155 155 0 170 170 0 182 182 0 193 193 0 204 204 0 202 202 0 201 201 0 191 191 0 101 40 40 102 41 41 104 42 42 105 43 43 107 43 43 109 44 44 110 45 45 112 46 46 114 47 47 116 48 48 48 19 19 48 19 19 48 19 19 48 19 19 48 19 19 48 19 19 48 19 19 48 19 19 127 55 55 127 55 55 127 55 55 126 54 54 125 53 53 123 53 53 122 52 52 120 51 51 118 50 50 117 49 49 115 47 47 113 46 46 111 46 46 109 45 45 108 44 44 106 43 43 105 42 42 103 42 42 102 41 41 101 40 40 99 40 40 98 39 39 97 39 39 96 38 38 95 38 38 94 37 37 93 37 37 91 36 36 85 34 34 86 34 34 87 35 35 88 35 35 126 126 0 144 144 0 158 158 0 169 169 0 179 179 0 196 196 0 236 236 4 240 240 4 205 205 0 199 199 0 190 190 0 101 41 41 103 41 41 104 42 42 106 43 43 107 44 44 109 44 44 111 45 45 112 46 46 47 19 19 47 19 19 47 19 19 47 19 19 47 19 19 47 19 19 47 19 19 47 19 19 47 19 19 47 19 19 125 53 53 124 53 53 123 53 53 122 52 52 121 51 51 120 51 51 118 50 50 117 49 49 115 48 48 113 47 47 112 46 46 110 45 45 108 44 44 107 43 43 105 43 43 104 42 42 103 41 41 101 41 41 100 40 40 99 39 39 98 39 39 96 38 38 95 38 38 94 38 38 93 37 37 92 37 37 91 36 36 17 49 17 17 49 17 18 50 18 110 110 0 127 127 0 141 141 0 152 152 0 162 162 0 170 170 0 177 177 0 183 183 0 188 188 0 191 191 0 191 191 0 187 187 0 175 175 0 21 58 21 21 58 21 21 58 21 21 59 21 22 59 22 22 60 22 22 60 22 22 60 22 22 61 22 20 50 20 20 50 20 20 50 20 20 50 20 20 50 20 20 50 20 20 50 20 20 50 20 20 50 20 23 62 23 23 61 23 23 61 23 22 61 22 22 61 22 22 61 22 22 60 22 22 60 22 22 60 22 22 59 22 21 59 21 21 58 21 21 58 21 21 57 21 21 57 21 20 56 20 20 56 20 20 55 20 20 55 20 19 54 19 19 54 19 19 53 19 19 52 19 18 52 18 18 51 18 18 51 18 21 58 21 21 59 21 90 90 0 108 108 0 122 122 0 133 133 0 143 143 0 152 152 0 159 159 0 166 166 0 193 193 1 210 210 3 179 179 0 179 179 0 176 176 0 169 169 0 145 145 0 26 69 26 26 69 26 26 70 26 26 70 26 27 70 27 27 71 27 27 71 27 27 72 27 27 72 27 27 72 27 27 72 27 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 28 73 28 27 72 27 27 72 27 27 72 27 27 72 27 27 71 27 27 71 27 27 70 27 26 70 26 26 69 26 26 69 26 26 68 26 25 68 25 25 67 25 25 67 25 25 66 25 24 65 24 24 65 24 24 64 24 24 63 24 23 63 23 23 62 23 25 66 25 66 66 0 88 88 0 102 102 0 113 113 0 123 123 0 132 132 0 140 140 0 147 147 0 154 154 0 235 235 13 255 255 39 169 169 0 164 164 0 162 162 0 156 156 0 141 141 0 29 76 29 29 77 29 30 77 30 30 78 30 30 78 30 30 79 30 31 79 31 31 80 31 31 80 31 31 80 31 31 81 31 31 81 31 31 81 31 32 81 32 32 82 32 32 82 32 32 82 32 32 82 32 32 82 32 32 82 32 32 82 32 32 82 32 32 82 32 32 81 32 31 81 31 31 81 31 31 81 31 31 80 31 31 80 31 31 80 31 31 79 31 30 79 30 30 78 30 30 78 30 30 77 30 29 77 29 29 76 29 29 75 29 29 75 29 28 74 28 28 74 28 28 73 28 28 72 28 27 72 27 66 66 0 82 82 0 94 94 0 104 104 0 112 112 0 120 120 0 127 127 0 134 134 0 139 139 0 145 145 0 149 149 0 148 148 0 148 148 0 146 146 0 140 140 0 127 127 0 32 82 32 32 83 32 33 84 33 33 84 33 33 85 33 33 85 33 33 85 33 34 86 34 34 86 34 34 87 34 34 87 34 34 87 34 34 88 34 34 88 34 35 88 35 35 88 35 35 88 35 35 89 35 35 89 35 35 89 35 22 57 22 22 57 22 22 57 22 22 57 22 22 57 22 22 57 22 22 57 22 34 88 34 34 88 34 34 87 34 34 87 34 34 87 34 34 86 34 34 86 34 33 85 33 33 85 33 33 84 33 33 84 33 32 83 32 32 83 32 32 82 32 32 81 32 31 81 31 30 77 30 64 64 0 78 78 0 89 89 0 98 98 0 107 107 0 114 114 0 120 120 0 125 125 0 130 130 0 133 133 0 135 135 0 136 136 0 135 135 0 132 132 0 125 125 0 110 110 0 34 87 34 34 88 34 35 88 35 35 89 35 35 89 35 35 90 35 36 90 36 36 91 36 36 91 36 36 91 36 36 92 36 36 92 36 37 92 37 37 93 37 37 93 37 37 93 37 37 93 37 37 94 37 37 94 37 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 24 61 24 37 92 37 36 92 36 36 92 36 36 91 36 36 91 36 36 90 36 35 90 35 35 90 35 35 89 35 35 88 35 35 88 35 31 81 31 60 60 0 73 73 0 83 83 0 92 92 0 100 100 0 106 106 0 112 112 0 117 117 0 121 121 0 124 124 0 125 125 0 126 126 0 124 124 0 121 121 0 113 113 0 97 97 0 36 91 36 36 91 36 36 92 36 37 92 37 37 93 37 37 93 37 37 94 37 37 94 37 38 95 38 38 95 38 38 95 38 38 96 38 38 96 38 38 96 38 38 97 38 39 97 39 39 97 39 39 97 39 39 98 39 39 98 39 39 98 39 39 98 39 26 65 26 26 65 26 26 65 26 26 65 26 26 65 26 26 65 26 26 65 26 26 65 26 26 65 26 26 65 26 39 97 39 39 97 39 38 97 38 38 96 38 38 96 38 38 96 38 38 95 38 38 95 38 37 95 37 37 94 37 37 94 37 33 85 33 54 54 0 66 66 0 76 76 0 84 84 0 92 92 0 98 98 0 103 103 0 107 107 0 111 111 0 113 113 0 115 115 0 115 115 0 113 113 0 108 108 0 99 99 0 77 77 0 37 94 37 37 94 37 38 95 38 38 95 38 38 96 38 38 96 38 38 97 38 39 97 39 39 98 39 39 98 39 39 98 39 39 99 39 39 99 39 40 99 40 40 100 40 40 100 40 40 100 40 40 100 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 101 40 40 100 40 40 100 40 40 100 40 40 100 40 40 99 40 39 99 39 39 99 39 39 98 39 34 87 34 54 54 0 58 58 0 68 68 0 76 76 0 82 82 0 88 88 0 93 93 0 97 97 0 100 100 0 102 102 0 103 103 0 102 102 0 99 99 0 93 93 0 81 81 0 38 96 38 38 96 38 38 97 38 39 97 39 39 98 39 39 98 39 39 99 39 39 99 39 40 99 40 40 100 40 40 100 40 40 101 40 40 101 40 40 101 40 40 102 40 41 102 41 41 102 41 41 102 41 41 103 41 41 103 41 41 103 41 41 103 41 41 103 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 104 41 41 103 41 41 103 41 41 103 41 41 103 41 41 103 41 41 102 41 41 102 41 21 54 21 54 54 0 54 54 0 58 58 0 66 66 0 72 72 0 78 78 0 82 82 0 86 86 0 88 88 0 89 89 0 89 89 0 88 88 0 83 83 0 75 75 0 39 97 39 39 98 39 39 98 39 39 99 39 40 99 40 40 100 40 40 100 40 40 100 40 40 101 40 40 101 40 41 102 41 41 102 41 41 102 41 41 103 41 41 103 41 41 103 41 41 104 41 41 104 41 42 104 42 42 104 42 42 105 42 42 105 42 42 105 42 42 105 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 106 42 42 105 42 42 105 42 42 105 42 21 54 21 21 54 21 54 54 0 54 54 0 54 54 0 61 61 0 66 66 0 70 70 0 73 73 0 75 75 0 75 75 0 74 74 0 71 71 0 64 64 0 22 54 22 39 99 39 40 100 40 40 100 40 40 100 40 40 101 40 40 101 40 41 102 41 41 102 41 41 102 41 41 103 41 41 103 41 41 104 41 41 104 41 42 104 42 42 105 42 42 105 42 42 105 42 42 105 42 42 106 42 42 106 42 42 106 42 43 106 43 43 107 43 43 107 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 107 43 43 107 43 21 54 21 21 54 21 21 54 21 54 54 0 54 54 0 54 54 0 54 54 0 56 56 0 58 58 0 59 59 0 59 59 0 56 56 0 54 54 0 12 29 12 26 66 26 26 66 26 40 101 40 40 101 40 41 102 41 41 102 41 41 103 41 41 103 41 41 103 41 41 104 41 42 104 42 42 104 42 42 105 42 42 105 42 42 106 42 42 106 42 42 106 42 43 106 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 43 108 43 43 108 43 43 108 43 43 109 43 43 109 43 43 109 43 43 109 43 44 109 44 44 109 44 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 44 110 44 44 110 44 44 110 44 44 109 44 44 109 44 44 109 44 44 109 44 43 109 43 21 54 21 21 54 21 12 29 12 12 29 12 12 29 12 54 54 0 54 54 0 54 54 0 54 54 0 54 54 0 54 54 0 12 29 12 26 67 26 27 67 27 27 67 27 27 67 27 41 102 41 41 103 41 41 103 41 41 103 41 41 104 41 42 104 42 42 105 42 42 105 42 42 105 42 42 106 42 42 106 42 43 106 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 43 108 43 43 108 43 43 109 43 43 109 43 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 44 110 44 44 110 44 44 110 44 44 110 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 12 29 12 12 29 12 12 29 12 12 29 12 12 29 12 12 29 12 12 29 12 12 29 12 12 29 12 27 67 27 27 67 27 27 67 27 27 67 27 27 68 27 27 68 27 41 103 41 41 103 41 41 104 41 42 104 42 42 104 42 42 105 42 42 105 42 42 106 42 42 106 42 43 106 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 43 108 43 43 108 43 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 44 110 44 44 110 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 44 111 44 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 26 65 26 26 65 26 26 65 26 26 66 26 26 66 26 26 66 26 26 66 26 27 67 27 27 67 27 27 67 27 27 68 27 27 68 27 27 68 27 27 69 27 41 103 41 42 104 42 42 104 42 42 105 42 42 105 42 42 105 42 42 106 42 43 106 43 43 106 43 43 107 43 43 107 43 43 108 43 43 108 43 43 108 43 43 108 43 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 44 110 44 44 111 44 44 111 44 44 111 44 44 111 44 45 111 45 45 111 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 26 66 26 26 66 26 26 66 26 26 66 26 27 67 27 27 67 27 27 67 27 27 68 27 27 68 27 27 68 27 27 68 27 27 69 27 41 104 41 42 104 42 42 104 42 42 105 42 42 105 42 42 105 42 42 106 42 43 106 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 43 108 43 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 44 110 44 44 111 44 44 111 44 45 111 45 45 111 45 45 111 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 114 45 45 114 45 45 114 45 45 114 45 45 114 45 45 114 45 45 114 45 26 66 26 27 67 27 27 67 27 27 67 27 27 67 27 27 68 27 27 68 27 27 68 27 27 69 27 41 103 41 41 104 41 42 104 42 42 104 42 42 105 42 42 105 42 42 106 42 42 106 42 43 106 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 44 108 44 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 44 111 44 45 111 45 45 111 45 45 111 45 45 111 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 114 45 45 114 45 45 114 45 45 114 45 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 27 67 27 27 67 27 27 68 27 41 102 41 41 102 41 41 102 41 41 103 41 41 103 41 41 104 41 42 104 42 42 104 42 42 105 42 42 105 42 42 106 42 43 106 43 43 106 43 43 107 43 43 107 43 43 107 43 43 108 43 43 108 43 44 108 44 44 109 44 44 109 44 44 109 44 44 110 44 44 110 44 44 110 44 45 111 45 45 111 45 45 111 45 45 111 45 45 112 45 45 112 45 45 112 45 45 112 45 45 112 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 113 45 45 114 45 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 114 46 46 115 46 46 115 46 46 115 46 46 115 46 46 115 46 46 115 46 46 115 46 46 115 46 
</details>

**Comment by adisonyheathcott** [comment]
This should now be fixed and the command should work properly. Thanks!

**Comment by cdecompilador** [comment]
Still it isn't, in my case I tried to open a big ppm (4k) and fails

![image](https://user-images.githubusercontent.com/36774000/101527291-16777980-398e-11eb-877e-71f561eef3ae.png)

Here is the big image:
[image.zip](https://github.com/adisonyheathcott/PPMViewer/files/5661181/image.zip)
